steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/chumzr-backend:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/chumzr-backend:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'chumzr-backend'
      - '--image=gcr.io/$PROJECT_ID/chumzr-backend:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--set-env-vars=NODE_ENV=production'
      - '--port=8080'
      - '--timeout=300s'

images:
  - 'gcr.io/$PROJECT_ID/chumzr-backend:$COMMIT_SHA'

substitutions:
  _REGION: us-central1  # Default region
  _SERVICE_NAME: chumzr-backend  # Default service name

options:
  logging: CLOUD_LOGGING_ONLY 