services:
  - type: web
    name: chumzr-backend
    env: node
    region: oregon # Choose the appropriate region for your needs
    plan: starter # Choose the appropriate plan (free, starter, etc.)
    buildCommand: ./build.sh
    startCommand: ./start.sh
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 # Render assigns its own port
      - key: MONGODB_URI
        sync: false # This will be set manually in the Render dashboard
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_API_KEY
        sync: false
      - key: BUNNY_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    autoDeploy: true # Enable automatic deployments
    disk:
      name: chumzr-uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1 # Size in GB, adjust as needed 